import Head from 'next/head'
import axios from 'axios'
import {useState} from 'react'
import Clima from '../components/Clima'
import Image from 'next/image';

export default function Home() {
  const [city, setCity] = useState(`${process.env.NEXT_PUBLIC_CIUDAD_NAME}`);
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);
 
  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}&units=metric`;
  console.log(city);
  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    axios.get(url).then((response) => {
      setWeather(response.data);
          });
    setCity('');
    setLoading(false);
  };

  return (
    <div>
      <Head>
        <title>El Clima</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
         <div >
         
          <h1 className='text-4xl text-center pb-6'>
            El Clima
          </h1>
         </div>
      <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 text-white z-10'>
       <form >
        <div>
        <input onChange={(e) => setCity(e.target.value)} type="text" placeholder='Ingresa tu Ciudad'></input>
        
        </div>

       </form>
        
       <button onClick={fetchWeather}>
              Buscar Ciudad
            </button>
      </div>
      {weather.main && <Clima data={weather} />}
      
    </div>
  )
}
